name: Continuous Integration

on:
  push:
    branches:
      - "1.x"
      - "2.x"
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        versions:
          - branch: "1.x"
            build_version: "1"
            factorio_version: "2.0"
            recycler_dependency: ''
          - branch: "2.x"
            build_version: "2"
            factorio_version: "2.1"
            recycler_dependency: '\"? recycler\",'

    steps:
      - name: Checkout ${{ matrix.versions.branch }}
        uses: actions/checkout@v7
        with:
          ref: ${{ matrix.versions.branch }}

      - id: download-mods-list
        name: Download mods list
        run: response=$(curl --silent --output mods.json --write-out "%{http_code}" "https://mods.factorio.com/api/mods?version=${{ matrix.versions.factorio_version }}&page_size=max"); echo "response=$response" >> $GITHUB_OUTPUT

      - id: current-version
        name: Get current version from info.json
        run: echo "current_version=$(jq -r '.version' info.json)" >> $GITHUB_OUTPUT

      - id: update-dependencies
        name: Update dependencies in info.json
        if: steps.download-mods-list.outputs.response == '200'
        run: |
          jq "{name: \"khaosdata-extractor\", title: \"QuingKhaos' Data Extractor\", description: \"Extracts data from Factorio for further validation, mocking, testing and more.\", author: \"QuingKhaos\", homepage: \"https://discord.gg/SYmkaDjFCt\", version: \"${{ steps.current-version.outputs.current_version }}\", factorio_version: \"${{ matrix.versions.factorio_version }}\", dependencies: [\"base\", \"? elevated-rails\", ${{ matrix.versions.recycler_dependency }} \"? quality\", \"? space-age\", (.results | sort_by(.name)[] | select(.name != \"khaosdata-extractor\") | \"? \" + .name)], package: {ignore: [\"mod_info.yml\", \"**/*.svg\", \"**/*.xcf\"]}}" mods.json > info.json

      - id: commit-dependencies
        name: Commit updated dependencies
        if: steps.download-mods-list.outputs.response == '200'
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "chore(deps): update mods from mod portal"
          branch: ${{ matrix.versions.branch }}
          file_pattern: |
            info.json

      - id: bump-version
        name: Bump version
        if: steps.commit-dependencies.outputs.changes_detected == 'true' || github.event_name == 'workflow_dispatch' || github.event_name == 'push'
        run: |
          new_version="${{ matrix.versions.build_version }}$(date +%Y.%m%d.%H%M)"
          sed -i "s/\"version\": \"\([0-9]*\)\.\([0-9]*\)\.\([0-9]*\)\"/\"version\": \"$new_version\"/" info.json
          sed -i "s/0\.0\.0/$new_version/" changelog.txt
          echo "new_version=$new_version" >> $GITHUB_OUTPUT

      - id: commit-version
        name: Commit new version
        if: steps.bump-version.outputs.new_version != ''
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "chore(release): v${{ steps.bump-version.outputs.new_version }}"
          branch: ${{ matrix.versions.branch }}
          file_pattern: |
            info.json
            changelog.txt

      - id: create-mod-package
        name: Create mod package
        if: steps.bump-version.outputs.new_version != ''
        uses: TheBrutalX/factorio-mod-uploader-action@v2
        with:
          action: compress
          mod-name: khaosdata-extractor
          mod-folder: ${{ github.workspace }}
          mod-version: ${{ steps.bump-version.outputs.new_version }}
          auto-update-version: false

      - name: Release mod package
        if: env.ZIP_FILE != ''
        uses: softprops/action-gh-release@v3
        with:
          name: ${{ steps.bump-version.outputs.new_version }}
          tag_name: v${{ steps.bump-version.outputs.new_version }}
          target_commitish: ${{ steps.commit-dependencies.outputs.commit_hash }}
          files: |
            ${{ env.ZIP_FILE }}
          fail_on_unmatched_files: true
          make_latest: true
          token: ${{ secrets.PUBLISH_RELEASE_PAT }}
